import { PoolSettings } from "../model/pool";
import { tokensMap } from "./tokens";
import { FeeAmount } from "@uniswap/v3-sdk";

// NOTE: If you want to create native pool, you should specify either
//       token0 or token1 as tokensMap.WLUX.
//       The script will wrap the native currency to WLUX.

export const POOL_CONFIGS: PoolSettings[] = [
    {
        token0: tokensMap.WLUX!,
        token1: tokensMap.LBTC!,
        type: "v3",
        fee: FeeAmount.MEDIUM,
        initialPrice: 0.0001,
        minPrice: 0.00005,
        maxPrice: 100000,
        amount0: 1,
        amount1: 1000,
    },
    {
        token0: tokensMap.WLUX!,
        token1: tokensMap.LPOL!,
        type: "v3",
        fee: FeeAmount.MEDIUM,
        initialPrice: 0.0001,
        minPrice: 0.00005,
        maxPrice: 100000,
        amount0: 1,
        amount1: 1000,
    },
    {
        token0: tokensMap.WLUX!,
        token1: tokensMap.LBNB!,
        type: "v3",
        fee: FeeAmount.MEDIUM,
        initialPrice: 0.0001,
        minPrice: 0.00005,
        maxPrice: 100000,
        amount0: 1,
        amount1: 1000,
    },
    {
        token0: tokensMap.WLUX!,
        token1: tokensMap.LFTM!,
        type: "v3",
        fee: FeeAmount.LOW,
        initialPrice: 0.0001,
        minPrice: 0.00005,
        maxPrice: 100000,
        amount0: 1,
        amount1: 1000,
    },
    {
        token0: tokensMap.WLUX!,
        token1: tokensMap.LCELO!,
        type: "v3",
        fee: FeeAmount.LOW,
        initialPrice: 0.0001,
        minPrice: 0.00005,
        maxPrice: 100000,
        amount0: 1,
        amount1: 1000,
    },
    {
        token0: tokensMap.WLUX!,
        token1: tokensMap.LUSD!,
        type: "v3",
        fee: FeeAmount.LOW,
        initialPrice: 0.0001,
        minPrice: 0.00005,
        maxPrice: 100000,
        amount0: 1,
        amount1: 1000,
    },
    {
        token0: tokensMap.WLUX!,
        token1: tokensMap.LETH!,
        type: "v3",
        fee: FeeAmount.LOW,
        initialPrice: 0.0001,
        minPrice: 0.00005,
        maxPrice: 100000,
        amount0: 1,
        amount1: 1000,
    },
    {
        token0: tokensMap.WLUX!,
        token1: tokensMap.LXDAI!,
        type: "v3",
        fee: FeeAmount.LOW,
        initialPrice: 0.0001,
        minPrice: 0.00005,
        maxPrice: 100000,
        amount0: 1,
        amount1: 1000,
    },
    {
        token0: tokensMap.LPOL!,
        token1: tokensMap.LBNB!,
        type: "v3",
        fee: FeeAmount.LOW,
        initialPrice: 0.0001,
        minPrice: 0.00005,
        maxPrice: 100000,
        amount0: 1,
        amount1: 1000,
    },
    {
        token0: tokensMap.LUSD!,
        token1: tokensMap.LFTM!,
        type: "v3",
        fee: FeeAmount.LOW,
        initialPrice: 0.0001,
        minPrice: 0.00005,
        maxPrice: 100000,
        amount0: 1,
        amount1: 1000,
    },
    {
        token0: tokensMap.LXDAI!,
        token1: tokensMap.LUSD!,
        type: "v3",
        fee: FeeAmount.LOW,
        initialPrice: 0.0001,
        minPrice: 0.00005,
        maxPrice: 100000,
        amount0: 1,
        amount1: 1000,
    },
    {
        token0: tokensMap.LXDAI!,
        token1: tokensMap.LBNB!,
        type: "v2",
        amount0: 100,
        amount1: 1000,
    },
    {
        token0: tokensMap.WLUX!,
        token1: tokensMap.LETH!,
        type: "v2",
        amount0: 1000,
        amount1: 1,
    },
]
