/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SafeMigrationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIGRATION_SINGLETON"
      | "SAFE_FALLBACK_HANDLER"
      | "SAFE_L2_SINGLETON"
      | "SAFE_SINGLETON"
      | "migrateL2Singleton"
      | "migrateL2WithFallbackHandler"
      | "migrateSingleton"
      | "migrateWithFallbackHandler"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ChangedMasterCopy"): EventFragment;

  encodeFunctionData(
    functionFragment: "MIGRATION_SINGLETON",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_FALLBACK_HANDLER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_L2_SINGLETON",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_SINGLETON",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrateL2Singleton",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrateL2WithFallbackHandler",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrateSingleton",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrateWithFallbackHandler",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MIGRATION_SINGLETON",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_FALLBACK_HANDLER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_L2_SINGLETON",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_SINGLETON",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateL2Singleton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateL2WithFallbackHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateSingleton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateWithFallbackHandler",
    data: BytesLike
  ): Result;
}

export namespace ChangedMasterCopyEvent {
  export type InputTuple = [singleton: AddressLike];
  export type OutputTuple = [singleton: string];
  export interface OutputObject {
    singleton: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SafeMigration extends BaseContract {
  connect(runner?: ContractRunner | null): SafeMigration;
  waitForDeployment(): Promise<this>;

  interface: SafeMigrationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIGRATION_SINGLETON: TypedContractMethod<[], [string], "view">;

  SAFE_FALLBACK_HANDLER: TypedContractMethod<[], [string], "view">;

  SAFE_L2_SINGLETON: TypedContractMethod<[], [string], "view">;

  SAFE_SINGLETON: TypedContractMethod<[], [string], "view">;

  migrateL2Singleton: TypedContractMethod<[], [void], "nonpayable">;

  migrateL2WithFallbackHandler: TypedContractMethod<[], [void], "nonpayable">;

  migrateSingleton: TypedContractMethod<[], [void], "nonpayable">;

  migrateWithFallbackHandler: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIGRATION_SINGLETON"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SAFE_FALLBACK_HANDLER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SAFE_L2_SINGLETON"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SAFE_SINGLETON"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "migrateL2Singleton"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "migrateL2WithFallbackHandler"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "migrateSingleton"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "migrateWithFallbackHandler"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ChangedMasterCopy"
  ): TypedContractEvent<
    ChangedMasterCopyEvent.InputTuple,
    ChangedMasterCopyEvent.OutputTuple,
    ChangedMasterCopyEvent.OutputObject
  >;

  filters: {
    "ChangedMasterCopy(address)": TypedContractEvent<
      ChangedMasterCopyEvent.InputTuple,
      ChangedMasterCopyEvent.OutputTuple,
      ChangedMasterCopyEvent.OutputObject
    >;
    ChangedMasterCopy: TypedContractEvent<
      ChangedMasterCopyEvent.InputTuple,
      ChangedMasterCopyEvent.OutputTuple,
      ChangedMasterCopyEvent.OutputObject
    >;
  };
}
